#!/bin/bash
sudo apt-get update
sudo apt-get install ruby -y
sudo apt-get install wget -y
sudo wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
sudo chmod +x ./install
sudo ./install auto
sudo apt-get install docker.io -y
sudo systemctl enable docker.service
sudo systemctl start docker.service
sudo git clone https://github.com/Aparna-SJ/codedeploy-container.git
sudo cp /codedeploy-container/scripts/Dockerfile.txt /opt/codedeploy-agent/
sudo cp /codedeploy-container/index.html /opt/codedeploy-agent/

