#!/bin/bash
sudo apt-get update
sudo apt-get install ruby -y
sudo apt-get install wget -y
sudo wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
sudo chmod +x ./install
sudo ./install auto
sudo apt-get install docker.io -y
sudo systemctl enable docker.service
sudo systemctl start docker.service
sudo echo "FROM ubuntu
MAINTAINER krishna
RUN apt-get update && apt-get install apache2 -y
RUN service apache2 start
RUN echo "<h1>Hello World to Earth</h1>" > /var/www/html/index.html
ENTRYPOINT apachectl -D FOREGROUND
EXPOSE 80" > /opt/codedeploy-agent/Dockerfile.txt
sudo docker build -t test:1 -f /opt/codedeploy-agent/Dockerfile.txt .
