#!/bin/bash
sudo apt-get update
sudo apt-get install ruby -y
sudo apt-get install wget -y
sudo wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
sudo chmod +x ./install
sudo ./install auto
sudo apt-get install docker.io -y
sudo systemctl enable docker.service
sudo systemctl start docker.service

